# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39fac580c0f959549713e15fc8513fa311c8f60a6c9180b60c6c2e82f82ada346bcfdc42eb0c75e92093523833fb4ec53ce6cb6890016d94b23c9c94bc8df6ca

test:
  secret_key_base: cfbbe141faeba02f614d0011a1205922e16854b441a2a2f2e5b709f9a39328f79fa3ab4626308b81c07785c9fe9d933def79bfd7e5f308a608020d3b9d6618c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
